import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={'flex flex-col min-h-screen'}>

          {/* Header */}
          <div className={'bg-teal-700 p-3 w-full'}>
            <span className={'bold text-white text-lg'}>
              Kreator Karty Bankowej
            </span>
          </div>

          {children}
          
          {/* Footer */}
          <div className={'bg-teal-700 p-3 bottom-0 w-full'}>
            <span className={'bold text-white text-sm'}>
              Autor strony: <br/>
              Filip Sankowski
            </span>
          </div>

        </div>
      </body>
    </html>
  )
}
